# 数据源配置
spring:
  datasource:
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    db:
      # 主数据源，默认为master
      master:
        url: jdbc:mysql://127.0.0.1:3306/lc-co-admin-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # 从数据源，slave
      slave:
        url: jdbc:mysql://127.0.0.1:3306/lc-co-admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      # quartz 定时任务数据源
      quartz:
        url: jdbc:mysql://127.0.0.1:3306/lc-co-admin-vue-quartz?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    # 初始连接数
    initial-size: 5
    # 最小连接池数量
    min-idle: 10
    # 最大连接池数量
    max-active: 20
    # 获取连接等待超时的时间
    max-wait: 60000
    # 检测间隔时间，检测需要关闭的空闲连接，单位毫秒
    time-between-eviction-runs-millis: 60000
    # 一个连接在连接池中最小的生存时间，单位毫秒
    min-evictable-idle-time-millis: 300000
    # 一个连接在连接池中最大的生存时间，单位毫秒
    max-evictable-idle-time-millis: 900000
    # 配置检测连接是否有效
    validation-query: SELECT 1 FROM DUAL
    # 如果为true（默认为false），当应用向连接池申请连接时，连接池会判断这条连接是否是可用的
    test-on-borrow: false
    # 连接返回检测
    test-on-return: false
    # 失效连接检测
    test-while-idle: true
    druid:
      #   开启web stat统计功能
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，缺省为所有
        allow:
        #  url匹配规则
        url-pattern: /druid/*
        # 控制面板登录用户名及密码
        login-username: admin
        login-password: 123456
        #  开启重置
        reset-enable: true
      filter:
        # 开启统计功能
        stat:
          enabled: true
          # 开启慢查询功能
          log-slow-sql: true
          slow-sql-millis: 1000
          # 合并多SQL
          merge-sql: true
        # 开启防火墙功能
        wall:
          enabled: true
          config:
            # 允许多语句同时执行
            multi-statement-allow: true
            # 允许一次执行多条语句
            none-base-statement-allow: true
      #   spring监控aop代理规则
      aop-patterns: org.lc.admin.system.mapper.*
    #    过滤器，多个用,隔开
    filters: stat,wall,log4j2