# 项目相关配置
admin:
  name: lc-co-admin
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/admin，Linux配置 /home/admin）
  profile: D:/admin
  # 获取ip地址开关
  addressEnabled: true
  # 验证码干扰类型
  captchaDisturbType: line

server:
  #  端口号
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
spring:
  application:
    #    应用名
    name: lc-co-admin
  transaction:
    rollback-on-commit-failure: true
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  resources:
    #    禁用资源映射全局异常才能捕获到404异常
    add-mappings: false
  mvc:
    #    打开寻找不到处理器则抛出异常
    throw-exception-if-no-handler-found: true
    favicon:
      #   关闭favicon功能
      enabled: false
    hiddenmethod:
      filter:
        enabled: true
  redis:
    database: 0
    timeout: 3000
    password:
    # 单节点模式
    host: localhost
    port: 6379
    # redisson配置文件路径
    redisson:
      file: classpath:redisson.yaml

mybatis:
  # mapper映射xml为文件路径
  mapperLocations: classpath*:mapper/**/**/*.xml
  # 搜索指定包别名
  typeAliasesPackage: org.lc.admin.**.entities
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

logging:
  # log4j2日志配置文件
  config: classpath:log4j2.xml
  level:
    org.lc.admin: debug
    org.springframework: warn

  #  knife4j api doc 配置
knife4j:
  #  关闭跨域配置
  cors: false
  #  开启knife4j
  enable: true
  # 请求前缀
  pathMapping: /dev-api
  basic:
    #  开启认证
    enable: true
    # 用户名与密码
    username: admin
    password: 123456

# 防止XSS注入
xss:
  # 过滤开关
  enabled: true
  # 排除url（多个用逗号分隔）
  excludes: /system/notice
  # 匹配url（多个用逗号分隔）
  urlPatterns: /system/*,/monitor/*,/tool/*
  # xss过滤等级
  level: none

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expiresTime: 30
  #  令牌刷新时间
  refreshTime: 20

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
  # 用户锁定时间（默认10分钟）
  lockTime: 10